kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-creater
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-secrets
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: secret-creater
  apiGroup: rbac.authorization.k8s.io
---
kind: Job
apiVersion: batch/v1
metadata:
  name: make-me-a-secret
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: generator
        image: replicated/k8s-secret-generator
        args:
        - '--name=my-secret'
        - '--key=my-key'
        - '--length=32'
        - '--base64encode'
        - '--namespace=default'
